apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: interstellar
        tier: frontend
    spec:
      containers:
      - name: nginx-fed
        image: nginx
        ports:
        - containerPort: 80